-- Your SQL goes here
CREATE TABLE urls (
    shortcode VARCHAR(255) PRIMARY KEY,
    link VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

